### PR TITLE
Content-Type aware response handler

### PR DESCRIPTION
**Pull request by fwal**
A take on creating an automatic response handler that reacts on the Content-Type header in the response rather than specifying the handleAs type up front.

### CODE REVIEW

**Comment by garlicnation** [comment]
Can you add a test for this?

**Comment by fwal** [comment]
Added tests but bumped into what seems to be a bug related to web-component-tester.
If I run the tests in parallell, the last one fails. But, if I run the last test alone it works fine.

**Comment by fwal** [comment]
Tests now fully functional.

**Comment by garlicnation** [comment]
Awesome! I'll check this out later today.

**Comment by fwal** [comment]
Sounds great!

**Comment by alecbenzer** [comment]
+1. Are there plans to merge this?

**Comment by fwal** [comment]
Polymer have evolved and this repo have moved to https://github.com/PolymerElements/iron-ajax
Also, the API have changed but I'm working on a new pr for that repo.

**Comment by fwal** [comment]
Here is the new PR: PolymerElements/iron-ajax#92

**Pull request closed without merging**
